version: '3.8'

services:
  api:
    image: ghcr.io/geon97/quantumtv:latest
    container_name: quantumtv-api
    ports:
      - '3086:3000'
    environment:
      - RUST_LOG=info
      # 默认订阅源
      - PARSES_URL=http://127.0.0.1
      # 默认订阅源文件，如果设置了，则不使用 PARSES_URL
      # 使用quantumtv app 导入的源文件即可
      - PARSES_FILE=crates/api-server/data.json
      # 服务器监听地址
      - SERVER_IP=127.0.0.1
      # 绑定地址
      - BIND_ADDR=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - quantumtv-network

networks:
  quantumtv-network:
    driver: bridge
